# This is a basic workflow to help you get started with Actions
name: CI
on:
  pull_request:
    branches: [ master ]
    types: ['labeled', 'synchronize','assigned','labeled','reopened','review_requested']

jobs:
  check_pr_milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: cchantep/probot-pr-status-label@ghaction-1.0.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        if: contains( github.event.pull_request.labels.*.name, 'patch')   
        uses: actions/checkout@master  
